### ISSUE TITLE
Override webpack revolve not working

### ISSUE THREAD

**Issue by MarvinAmador7** [storybooks/react-storybook#710] opened 2017-03-01 23:45 UTC
Hi guys I'm trying to define a webpack resolve in .storybook/webpack.config.js

`resolve : {
    modules : [
      path.resolve('./src'),
      'node_modules',
    ],
  },`

In order to use in my styles : 
`import variables from 'theme/varables';`
in the theme folder I have a package.json with 
`{
  "name" : "@theme"
}
`
webpack output : 
![react storybook 2017-03-01 17-45-11](https://cloud.githubusercontent.com/assets/13001660/23486624/d75dbb18-fea6-11e6-94e1-0e87abe2a95c.png)

Any idea? 
thanks

**Comment by MarvinAmador7** [comment] 2017-03-02 00:06
NVM this solve the issue https://github.com/tleunen/babel-plugin-module-resolver

**Comment by ndelangen** [comment] 2017-03-28 13:54
Can we close this issue ?

**Comment by ndelangen** [comment] 2017-04-05 22:50
Let us know if this issue still exist 👌 ?

**Closed by ndelangen** 2017-04-05 22:50 UTC
Labels: compatibility with other tools

**Comment by eric-burel** [comment] 2017-04-07 12:02
I can confirm this issue still happens. Using `babel-plugin-module-resolver` seems a quickfix to me, as it implies adding a new plugin only to get storybook working.

**Comment by eric-burel** [comment] 2017-04-07 13:02
Okay for anyone that encounter the same issue: that's because we must use `modulesDirectories` instead of modules for webpack v1, which Storybook use for the moment (v2.35).
[https://webpack.github.io/docs/resolving.html](https://webpack.github.io/docs/resolving.html)

**Comment by xavcz** [comment] 2017-04-07 14:06
Or shall we try to move to Webpack v2? 💃

**Comment by ndelangen** [comment] 2017-04-07 20:06
We will move over to webpack 2.
